print("Content-type:text/html\r\n\r\n")
print('<html>')
print('<head>')
print('<title>First CGI program</title>')
print('</head>')
print('<body>')
print('<h2>HELLO WORLD</h2>')
print('</body>')
print('</html>')